version: "3.8"

x-variables: &variables
  DB_USERNAME: ${DB_USERNAME}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: ${DB_HOST}
  DB_PORT: 3306
  DB_NAME: ${DB_NAME}
  APP_SERVICE_HOST: ${APP_SERVICE_HOST}
  ENCRYPT_SECRET_KEY: ${ENCRYPT_SECRET_KEY}
  JWT_SECRET_KEY: ${JWT_SECRET_KEY}

x-react-variables: &react-variables
  REACT_APP_API_BASEURL: http://localhost:8080
  REACT_APP_API: http://localhost:8080/api

services:
  # Database
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306

  # Maven Projects
  gateway:
    image: lyndasm/aline:aline-gateway
    ports:
      - 8080:8080
    environment:
      <<: *variables
      APP_PORT: 8080

  underwriter:
    image: lyndasm/aline:aline-underwriter
    depends_on:
      - mysql
    ports:
      - 8071:8071
    environment:
      <<: *variables
      APP_PORT: 8071

  user:
    image: lyndasm/aline:aline-user
    ports:
      - 8070:8070
    environment:
      <<: *variables
      APP_PORT: 8070

volumes:
  db-data:
