# smoke-test-data-generator\
#   __init__.py
#   main\
#     __init__.py
#     __main__.py
#     config.py
#     logging_handler.py
#     utils.py
#     tests\
#         __init__.py
#         test_applicant.py
#         test_user.py
#         test_utils.py
#     data_producers\
#         __init__.py
#         applicant.py
#         applicaiton.py
#         user.py
